version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - funlen
    - gocognit
    - gocyclo
    - intrange
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      verbose: true
    gocritic:
      enable-all: true
    govet:
      enable-all: true
    grouper:
      const-require-single-const: true
      const-require-grouping: true
      import-require-single-import: true
      import-require-grouping: true
      type-require-single-type: true
      type-require-grouping: true
      var-require-single-var: true
      var-require-grouping: true
    makezero:
      always: true
    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: cognitive-complexity
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: function-length
          disabled: true
        - name: identical-switch-branches
          disabled: true
        - name: line-length-limit
          arguments: [ 120 ]
        - name: package-directory-mismatch
          disabled: true
        - name: unhandled-error
          arguments:
            - "bytes.Buffer.Write"
            - "bytes.Buffer.WriteString"
            - "strings.Builder.WriteString"
    testifylint:
      enable-all: true
    unused:
      field-writes-are-uses: false
      post-statements-are-reads: false
      exported-fields-are-used: true
      parameters-are-used: false
      local-variables-are-used: false
      generated-is-used: true
  exclusions:
    generated: strict
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - err113
          - errname
          - grouper
          - revive
          - testpackage
          - varnamelen
    paths:
      - examples
