repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
      - id: go-build-mod
      - id: go-mod-tidy-repo
      - id: go-test-mod
      - id: my-cmd-repo
        name: lint-fix
        alias: lint-fix
        args: [ make, lint-fix ]

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-gofmt
          - mdformat-shfmt
          - mdformat-toc
